### ISSUE TITLE
Does this package need to exist, with pytorch-lightning package already in conda-forge?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/lightning-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Both this feedstock and the one for `pytorch-lightning` track the same project.  It is concerning that there are 2 packages in conda-forge currently tracking the same project.  Is this package necessary given the other one?  If so, then at least the dependencies should be kept consistent, as they are not currently.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by weiji14** [comment]
See https://github.com/conda-forge/staged-recipes/pull/22249#issuecomment-1468884067. The repo at https://github.com/Lightning-AI/lightning is a [monorepo](https://en.wikipedia.org/wiki/Monorepo) that produces the [`lightning`](https://pypi.org/project/lightning/) and [`pytorch-lightning`](https://pypi.org/project/pytorch-lightning/) packages. Yes they have the same version and appear similar, but `lightning` is `pytorch-lightning` + more stuff, see the `recipe/meta.yaml` file:

https://github.com/conda-forge/lightning-feedstock/blob/1f60964042f689bae78efbeeed2fd1469f9a71e9/recipe/meta.yaml#L26-L58

Hopefully that answers your issue, I'll close this issue now.

**Comment by dsuess** [comment]
How do these two packages interact with each other? Shouldn't there be some kind of version-constraint on the `pytorch-lightning` dependency used by `lightning`? 

(I understand that this question should probably go to the actual lightning repo since the pip package also does not specify any constraints)

**Comment by weiji14** [comment]
> Shouldn't there be some kind of version-constraint on the pytorch-lightning dependency used by lightning?

Best to raise it upstream in the lightning repo, the conda-forge recipe here is really just following the version pinnings from the PyPI package. I actually have no clue about how forward or backward compatible `lightning` is with `pytorch-lightning`, though I'd assume that lightning 2.0.x should work with pytorch-lightning 2.0.x.

**Comment by dsuess** [comment]
Thanks for the quick reply. If anyone stumbles across this here: https://github.com/Lightning-AI/lightning/discussions/17095#discussioncomment-6277660
